spring:
  docker:
    compose:
      lifecycle-management: start-and-stop
      file : docker-compose.yml
  application:
    name: spring-batch-exam
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-batch-db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
